version: '3.8'

services:
  app:
    build: .
    container_name: HaryPotter
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_APPLICATION_NAME=HaryPotter
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:potterdb
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update